# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Segment Routing"
title_separator          : "-"
name                     : &name "Cisco Systems Inc"
description              : &description "Documentation, Blogs and Tutorials for all things Segment Routing "
url                      : "https://www.segment-routing.net" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
gh_repo                  : "https://github.com/xrdocs/segment-routing"
teaser                   : "images/new-design/SR-Background-Image-3.png" # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
logo                     : "images/sr-logo-blue.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 200

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "segmentrouting"
og_image                 : "sr-logo-blue.png" # Open Graph/Twitter default site image

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-96386965-1"

# Site Author
author:
  name             : "Segment Routing Team"
  bio              : "Segment Routing, Cisco"
  email            : "ask-segment-routing@cisco.com"
  twitter          : "segmentrouting"
  linkedin-group   : "8266623"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache  
  - [vendor]
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: true


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:path/
  conferences:
    output: true
    permalink: /:collection/:path/
  open-software:
    output: true
    permalink: /:collection/:path/
  scientific-papers:
    output: true
    permalink: /:collection/:path/
  news: 
    output: true
    permalink: /:collection/:path/
  srv6-news:
    output: true
    permalink: /:collection/:path/
  srmpls-news:
    output: true
    permalink: /:collection/:path/
  demos:
    output: true
    permalink: /:collection/:path/    

# Defaults
defaults:
# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single-full
# _tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single-full
      read_time: false
      related: true
      position: "top"
# _conferences
  - scope:
      path: ""
      type: conferences
    values:
      layout: single-full
      read_time: false
      related: true
      position: "top"
# _open-software
  - scope:
      path: ""
      type: open-software
    values:
      layout: single-full
      related: true
      position: "top"
# _scientific-papers
  - scope:
      path: ""
      type: scientific-papers
    values:
      layout: single-full
      related: true
      position: "top"
# _news
  - scope:
      path: ""
      type: news
    values:
      layout: single-full
      read_time: false
      related: true
      position: "top"
# _demos
  - scope:
      path: ""
      type: demos
    values:
      layout: single-full
      read_time: false
      related: true
      position: "top"
# _srv6-news
  - scope:
      path: ""
      type: single-full
    values:
      layout: news
      read_time: false
      related: true
      position: "top"
# _srmpls-news
  - scope:
      path: ""
      type: single-full
    values:
      layout: news
      read_time: false
      related: true
      position: "top"

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone:  Europe/Madrid# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-redirect-from


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
categories:
  type: liquid
  path: /categories/
tags:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


prose:
  siteurl: 'https://xrdocs.github.io'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_sass
    - /_layouts
    - /_includes
    - /_posts
    - /_pages
    - /_docs
    - /_data/ui-test.yml
    - /_drafts
    - /_includes
    - /_layouts
    - /_pages
    - /_pets
    - /_portfolio
    - /_posts
    - /_recipes
    - /assets
    - /images
    - /_data/ui-text.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - _config.dev.yml
    - _config.yml
    - package.json
    - search_data.html
    - .jekyll-metadata
    - CHANGELOG.md
    - README.md
    - feed.xml
    - search.html
    - .travis.yml
    - _config.pdf.yml
    - _config.travis.yml
  metadata:
    _tutorials:
      - name: "title"
        field:
            element: "text"
            label: "Title"
            value: ""
      - name: "author"
        field:
            element: "text"
            label: "Author"
            value: "Segment Routing Team"
      - name: "excerpt"
        field:
            element: "text"
            help: "Brief description of the tutorial"
            label: "Excerpt"
      - name: "published"
        field:
            label: "Published"
            element: "checkbox"
            value: true
      - name: "breadnav"
        field:
            label: "breadnav"
            element: "checkbox"
            value: true
      - name: "date"
        field:
            element: "text"
            label: "Date"
            value: "CURRENT_DATETIME"
      - name: "order"
        field:
            element: "number"
            label: "order"
            value: "99"
    _conferences:
      - name: "title"
        field:
            element: "text"
            label: "Title"
            value: ""
      - name: "author"
        field:
            element: "text"
            label: "Author"
            value: "Segment Routing Team"
      - name: "excerpt"
        field:
            element: "text"
            help: "Brief description of the tutorial"
            label: "Excerpt"
      - name: "teaser"
        field:
            element: "text"
            help: "Provide a url for a teaser image for this conference/event"
            label: "teaser image"
            value: ""
      - name: "published"
        field:
            label: "Published"
            element: "checkbox"
            value: true
      - name: "breadnav"
        field:
            label: "breadnav"
            element: "checkbox"
            value: true
      - name: "date"
        field:
            element: "text"
            label: "Date"
            value: "CURRENT_DATETIME"
    _open-software:
      - name: "title"
        field:
            element: "text"
            label: "Title"
            value: ""
      - name: "author"
        field:
            element: "text"
            label: "Author"
            value: "Segment Routing Team"
      - name: "excerpt"
        field:
            element: "text"
            help: "Brief description of the tutorial"
            label: "Excerpt"
      - name: "published"
        field:
            label: "Published"
            element: "checkbox"
            value: true
      - name: "date"
        field:
            element: "text"
            label: "Date"
            value: "CURRENT_DATETIME"
    _scientific-papers:
      - name: "title"
        field:
            element: "text"
            label: "Title"
            value: ""
      - name: "author"
        field:
            element: "text"
            label: "Author"
            value: "Segment Routing Team"
      - name: "excerpt"
        field:
            element: "text"
            help: "Brief description of the tutorial"
            label: "Excerpt"
      - name: "published"
        field:
            label: "Published"
            element: "checkbox"
            value: true
      - name: "date"
        field:
            element: "text"
            label: "Date"
            value: "CURRENT_DATETIME"

sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

host: "0.0.0.0"
port: 4000
